# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulator_controller_pb2 as simulator__controller__pb2


class SimulatorControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.unary_unary(
                '/controller.SimulatorController/Step',
                request_serializer=simulator__controller__pb2.StepRequest.SerializeToString,
                response_deserializer=simulator__controller__pb2.StepResponse.FromString,
                )
        self.Position = channel.unary_unary(
                '/controller.SimulatorController/Position',
                request_serializer=simulator__controller__pb2.PositionRequest.SerializeToString,
                response_deserializer=simulator__controller__pb2.PositionResponse.FromString,
                )
        self.Time = channel.unary_unary(
                '/controller.SimulatorController/Time',
                request_serializer=simulator__controller__pb2.TimeRequest.SerializeToString,
                response_deserializer=simulator__controller__pb2.TimeResponse.FromString,
                )


class SimulatorControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Position(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Time(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=simulator__controller__pb2.StepRequest.FromString,
                    response_serializer=simulator__controller__pb2.StepResponse.SerializeToString,
            ),
            'Position': grpc.unary_unary_rpc_method_handler(
                    servicer.Position,
                    request_deserializer=simulator__controller__pb2.PositionRequest.FromString,
                    response_serializer=simulator__controller__pb2.PositionResponse.SerializeToString,
            ),
            'Time': grpc.unary_unary_rpc_method_handler(
                    servicer.Time,
                    request_deserializer=simulator__controller__pb2.TimeRequest.FromString,
                    response_serializer=simulator__controller__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.SimulatorController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulatorController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.SimulatorController/Step',
            simulator__controller__pb2.StepRequest.SerializeToString,
            simulator__controller__pb2.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Position(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.SimulatorController/Position',
            simulator__controller__pb2.PositionRequest.SerializeToString,
            simulator__controller__pb2.PositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Time(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/controller.SimulatorController/Time',
            simulator__controller__pb2.TimeRequest.SerializeToString,
            simulator__controller__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
